# Generated by Django 5.0.6 on 2024-07-07 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Registration Number')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('stations', models.ManyToManyField(related_name='evaluation_groups', to='ecoe.station')),
                ('students', models.ManyToManyField(related_name='evaluation_groups', to='ecoe.student')),
            ],
            options={
                'verbose_name': 'Evaluation Group',
                'verbose_name_plural': 'Evaluation Groups',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_score', models.FloatField(default=0, verbose_name='Station Score')),
                ('station_comment', models.TextField(blank=True, null=True, verbose_name='Station Comment')),
                ('evaluation_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoe.evaluationgroup', verbose_name='Evaluation Group')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoe.station', verbose_name='Station')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoe.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Evaluation Station',
                'verbose_name_plural': 'Evaluation Stations',
                'unique_together': {('evaluation_group', 'station', 'student')},
            },
        ),
    ]
