# Generated by Django 5.0.6 on 2024-06-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='rol',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default='prueba@test.com', max_length=50, verbose_name='Rol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluador',
            name='email',
            field=models.EmailField(default=1, max_length=50, verbose_name='Rol'),
            preserve_default=False,
        ),
    ]
