export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS'
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL'

export const GET_STUDENT_DETAIL_SUCCESS = 'GET_STUDENT_DETAIL_SUCCESS';
export const GET_STUDENT_DETAIL_FAIL = 'GET_STUDENT_DETAIL_FAIL';
