export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL';

export const GET_STUDENT_DETAIL_SUCCESS = 'GET_STUDENT_DETAIL_SUCCESS';
export const GET_STUDENT_DETAIL_FAIL = 'GET_STUDENT_DETAIL_FAIL';

export const GET_STUDENT_EVALUATIONS_SUCCESS = 'GET_STUDENT_EVALUATIONS_SUCCESS';
export const GET_STUDENT_EVALUATIONS_FAIL = 'GET_STUDENT_EVALUATIONS_FAIL';

export const GET_GROUP_EVALUATIONS_SUCCESS = 'GET_GROUP_EVALUATIONS_SUCCESS';
export const GET_GROUP_EVALUATIONS_FAIL = 'GET_GROUP_EVALUATIONS_FAIL';

export const GET_STUDENT_GROUPS_SUCCESS = 'GET_STUDENT_GROUPS_SUCCESS';
export const GET_STUDENT_GROUPS_FAIL = 'GET_STUDENT_GROUPS_FAIL';

export const GET_STUDENT_GROUP_EVALUATIONS_SUCCESS = 'GET_STUDENT_GROUP_EVALUATIONS_SUCCESS';
export const GET_STUDENT_GROUP_EVALUATIONS_FAIL = 'GET_STUDENT_GROUP_EVALUATIONS_FAIL';
